# Generated by Django 4.2.27 on 2026-04-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '__first__'),
        ('centerfrequencies', '__first__'),
        ('datatypes', '__first__'),
        ('instruments', '__first__'),
        ('stations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRate', models.IntegerField(verbose_name='Data rate')),
                ('size', models.BigIntegerField()),
                ('fileName', models.CharField(max_length=60, verbose_name='File')),
                ('plotFile', models.CharField(blank=True, max_length=60, null=True, verbose_name='Plot')),
                ('path', models.CharField(max_length=60)),
                ('plotPath', models.CharField(blank=True, max_length=40, null=True)),
                ('startDate', models.DateTimeField(verbose_name='Start Date (UTC)')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='End Date (UTC)')),
                ('band', models.ManyToManyField(blank=True, to='bands.band', verbose_name='Band')),
                ('centerFrequency', models.ManyToManyField(blank=True, to='centerfrequencies.centerfrequency', verbose_name='Center Frequency')),
                ('dataType', models.ManyToManyField(blank=True, to='datatypes.datatype', verbose_name='Data type')),
                ('instrument', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
