# Generated by Copilot on 2026-04-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
        ('datatypes', '__first__'),
        ('fileformats', '0001_initial'),
        ('filestatuses', '0001_initial'),
        ('producttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=60)),
                ('fileName', models.CharField(max_length=60)),
                ('size', models.BigIntegerField()),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('created_by_program', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('tags', models.CharField(blank=True, max_length=40, null=True)),
                ('DOI', models.CharField(blank=True, max_length=40, null=True)),
                ('Notes', models.CharField(blank=True, max_length=80, null=True)),
                ('dataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatypes.datatype')),
                ('fileFormat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileformats.fileformat')),
                ('fileStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filestatuses.filestatus')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observation')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producttypes.producttype')),
            ],
        ),
    ]