# Generated by Django 4.2.27 on 2026-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_dataproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='fileLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='observation',
            name='fileLevel',
            field=models.IntegerField(default=0),
        ),
    ]
